[package]
name = "dedup-sort"
version = "0.1.0"
edition = "2021"
authors = ["Nicolas Barrios <nbarrios1337@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
